
version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model

  dashboard:
    build:
      context: ./dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./model:/app/model
